// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('./src/4_components/atoms/aButton.vue')['default']
    AEmoji: typeof import('./src/4_components/atoms/aEmoji.vue')['default']
    AIcon: typeof import('./src/4_components/atoms/aIcon.vue')['default']
    ATextInput: typeof import('./src/4_components/atoms/aTextInput.vue')['default']
    'CDebug.dev': typeof import('./src/4_components/cDebug.dev.vue')['default']
    CModal: typeof import('./src/4_components/cModal.vue')['default']
    CNavbar: typeof import('./src/4_components/cNavbar.vue')['default']
    CSpellInput: typeof import('./src/4_components/cSpellInput.vue')['default']
    CSpellSingleLetter: typeof import('./src/4_components/cSpellSingleLetter.vue')['default']
    CTabsContainer: typeof import('./src/4_components/cTabsContainer.vue')['default']
  }
}

export { }
