[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "16"

[build]
  command = "npx pnpm i --store-dir=node_modules/.pnpm-store && npx pnpm run build"
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
