import { icons as unicons } from '@iconify-json/uil';
import { icons as fluent } from '@iconify-json/fluent';
import { icons as twemojis } from '@iconify-json/twemoji';
import { addIcon } from '@iconify/vue/offline';

const emojis: Record<string, string[][]> = {
  environment: [
    ['🌚', '1f31a', 'new-moon-face'],
    ['🌝', '1f31d', 'full-moon-face'],
    ['🌞', '1f31e', 'sun-with-face'],
    ['🌧️', '1f327', 'cloud-with-rain'],
    ['🌩️', '1f329', 'cloud-with-lightning'],
    ['⚡️', '26a1', 'high-voltage'],
    ['🌪️', '1f32a', 'tornado'],
    ['🌈', '1f308', 'rainbow'],
    ['☄️', '2604', 'comet'],
    ['✨', '2728', 'sparkles'],
    ['🌊', '1f30a', 'water-wave'],
    ['💦', '1f4a6', 'sweat-droplets'],
    ['🔥', '1f525', 'fire'],
    ['🌋', '1f30b', 'volcano'],
    ['🌱', '1f331', 'seedling'],
    ['🌷', '1f337', 'tulip'],
    ['🥀', '1f940', 'wilted-flower'],
    ['🍀', '1f340', 'four-leaf-clover'],
    ['🍄', '1f344', 'mushroom'],
    ['🌵', '1f335', 'cactus'],
  ],
  food: [
    ['🌶️', '1f336', 'hot-pepper'],
    ['🍆', '1f346', 'eggplant'],
    ['🍉', '1f349', 'watermelon'],
    ['🍋', '1f34b', 'lemon'],
    ['🍑', '1f351', 'peach'],
    ['🍓', '1f353', 'strawberry'],
    ['🍤', '1f364', 'fried-shrimp'],
    ['🍩', '1f369', 'doughnut'],
    ['🍳', '1f373', 'cooking'],
    ['🍿', '1f37f', 'popcorn'],
    ['🥂', '1f942', 'clinking-glasses'],
    ['🍹', '1f379', 'tropical-drink'],
    ['🥐', '1f950', 'croissant'],
    ['🥔', '1f954', 'potato'],
    ['🥚', '1f95a', 'egg'],
    ['🥦', '1f966', 'broccoli'],
    ['🧀', '1f9c0', 'cheese-wedge'],
    ['🧂', '1f9c2', 'salt'],
    ['🍵', '1f375', 'teacup-without-handle'],
    ['☕️', '2615', 'hot-beverage'],
  ],
  animals: [
    ['🐀', '1f400', 'rat'],
    ['🐿️', '1f43f', 'chipmunk'],
    ['🦔', '1f994', 'hedgehog'],
    ['🐇', '1f407', 'rabbit'],
    ['🐈&zwj;⬛', '1f408-200d-2b1b', 'black-cat'],
    ['🦁', '1f981', 'lion'],
    ['🐕', '1f415', 'dog'],
    ['🐄', '1f404', 'cow'],
    ['🐖', '1f416', 'pig'],
    ['🐎', '1f40e', 'horse'],
    ['🐐', '1f410', 'goat'],
    ['🦬', '1f9ac', 'bison'],
    ['🦨', '1f9a8', 'skunk'],
    ['🦝', '1f99d', 'raccoon'],
    ['🦫', '1f9ab', 'beaver'],
    ['🦦', '1f9a6', 'otter'],
    ['🦊', '1f98a', 'fox'],
    ['🐺', '1f43a', 'wolf'],
    ['🦌', '1f98c', 'deer'],
    ['🐨', '1f428', 'koala'],
    ['🐻&zwj;❄️', '1f43b-200d-2744-fe0f', 'polar-bear'],
    ['🐻', '1f43b', 'bear'],
    ['🐼', '1f43c', 'panda'],
    ['🐒', '1f412', 'monkey'],
    ['🐪', '1f42a', 'camel'],
    ['🐘', '1f418', 'elephant'],
    ['🦒', '1f992', 'giraffe'],
    ['🦓', '1f993', 'zebra'],
    ['🦘', '1f998', 'kangaroo'],
    ['🦛', '1f99b', 'hippopotamus'],
    ['🦏', '1f98f', 'rhinoceros'],
    ['🦥', '1f9a5', 'sloth'],
    ['🦇', '1f987', 'bat'],
    ['🐣', '1f423', 'hatching-chick'],
    ['🐦', '1f426', 'bird'],
    ['🐓', '1f413', 'rooster'],
    ['🐧', '1f427', 'penguin'],
    ['🕊️', '1f54a', 'dove'],
    ['🦅', '1f985', 'eagle'],
    ['🦢', '1f9a2', 'swan'],
    ['🦜', '1f99c', 'parrot'],
    ['🦉', '1f989', 'owl'],
    ['🦩', '1f9a9', 'flamingo'],
    ['🦚', '1f99a', 'peacock'],
    ['🦄', '1f984', 'unicorn'],
    ['🐉', '1f409', 'dragon'],
    ['🐊', '1f40a', 'crocodile'],
    ['🐍', '1f40d', 'snake'],
    ['🐸', '1f438', 'frog'],
    ['🦎', '1f98e', 'lizard'],
    ['🐢', '1f422', 'turtle'],
    ['🐠', '1f420', 'tropical-fish'],
    ['🐬', '1f42c', 'dolphin'],
    ['🦈', '1f988', 'shark'],
    ['🐋', '1f40b', 'whale'],
    ['🦑', '1f991', 'squid'],
    ['🦐', '1f990', 'shrimp'],
    ['🦪', '1f9aa', 'oyster'],
    ['🐌', '1f40c', 'snail'],
    ['🐛', '1f41b', 'bug'],
    ['🐝', '1f41d', 'honeybee'],
    ['🐞', '1f41e', 'lady-beetle'],
    ['🕷️', '1f577', 'spider'],
    ['🦋', '1f98b', 'butterfly'],
    ['🦗', '1f997', 'cricket'],
    ['🦟', '1f99f', 'mosquito'],
    ['🦀', '1f980', 'crab'],
    ['🦞', '1f99e', 'lobster'],
    ['🦂', '1f982', 'scorpion'],
    ['🦤', '1f9a4', 'dodo'],
  ],
  things: [
    ['🎉', '1f389', 'party-popper'],
    ['🎢', '1f3a2', 'roller-coaster'],
    ['🎨', '1f3a8', 'artist-palette'],
    ['🎭', '1f3ad', 'performing-arts'],
    ['🎲', '1f3b2', 'game-die'],
    ['🎶', '1f3b6', 'musical-notes'],
    ['🏁', '1f3c1', 'chequered-flag'],
    ['🏆', '1f3c6', 'trophy'],
    ['👁️', '1f441', 'eye'],
    ['👑', '1f451', 'crown'],
    ['👓', '1f453', 'glasses'],
    ['👹', '1f479', 'ogre'],
    ['👻', '1f47b', 'ghost'],
    ['✉️', '2709', 'envelope'],
    ['💎', '1f48e', 'gem-stone'],
    ['💫', '1f4ab', 'dizzy'],
    ['💰', '1f4b0', 'money-bag'],
    ['💸', '1f4b8', 'money-with-wings'],
    ['📜', '1f4dc', 'scroll'],
    ['🔮', '1f52e', 'crystal-ball'],
    ['🕯️', '1f56f', 'candle'],
    ['🗝️', '1f5dd', 'old-key'],
    ['🗡️', '1f5e1', 'dagger'],
    ['🚀', '1f680', 'rocket'],
    ['🚩', '1f6a9', 'triangular-flag'],
    ['🚪', '1f6aa', 'door'],
    ['🚸', '1f6b8', 'children-crossing'],
    ['🚽', '1f6bd', 'toilet'],
    ['🛠️', '1f6e0', 'hammer-and-wrench'],
    ['🛹', '1f6f9', 'skateboard'],
    ['🥊', '1f94a', 'boxing-glove'],
    ['🧨', '1f9e8', 'firecracker'],
    ['🧭', '1f9ed', 'compass'],
    ['🧲', '1f9f2', 'magnet'],
    ['🩹', '1fa79', 'adhesive-bandage'],
    ['🪃', '1fa83', 'boomerang'],
    ['🪄', '1fa84', 'magic-wand'],
    ['🪜', '1fa9c', 'ladder'],
    ['⌛️', '231b', 'hourglass-done'],
    ['⚖️', '2696', 'balance-scale'],
  ],
  faces: [
    ['😂', '1f602', 'face-with-tears-of-joy'],
    ['😇', '1f607', 'smiling-face-with-halo'],
    ['😈', '1f608', 'smiling-face-with-horns'],
    ['😏', '1f60f', 'smirking-face'],
    ['😒', '1f612', 'unamused-face'],
    ['😖', '1f616', 'confounded-face'],
    ['😡', '1f621', 'pouting-face'],
    ['😤', '1f624', 'face-with-steam-from-nose'],
    ['😬', '1f62c', 'grimacing-face'],
    ['😭', '1f62d', 'loudly-crying-face'],
    ['😱', '1f631', 'face-screaming-in-fear'],
    ['😳', '1f633', 'flushed-face'],
    ['😴', '1f634', 'sleeping-face'],
    ['😵&zwj;💫', '1f635-200d-1f4ab', 'face-with-spiral-eyes'],
    ['🙃', '1f643', 'upside-down-face'],
    ['🙄', '1f644', 'face-with-rolling-eyes'],
    ['🤐', '1f910', 'zipper-mouth-face'],
    ['🤓', '1f913', 'nerd-face'],
    ['🤔', '1f914', 'thinking-face'],
    ['🤠', '1f920', 'cowboy-hat-face'],
    ['🤢', '1f922', 'nauseated-face'],
    ['🤥', '1f925', 'lying-face'],
    ['🤪', '1f92a', 'zany-face'],
    ['🤯', '1f92f', 'exploding-head'],
    ['🥴', '1f974', 'woozy-face'],
    ['🥵', '1f975', 'hot-face'],
    ['🥶', '1f976', 'cold-face'],
    ['💀', '1f480', 'skull'],
    ['🤡', '1f921', 'clown-face'],
    ['🥸', '1f978', 'disguised-face'],
  ],
  hearts: [
    ['❤️', '2764', 'red-heart'],
    ['💘', '1f498', 'heart-with-arrow'],
    ['❤️&zwj;🔥', '2764-fe0f-200d-1f525', 'heart-on-fire'],
    ['💞', '1f49e', 'revolving-hearts'],
    ['💔', '1f494', 'broken-heart'],
    ['❤️&zwj;🩹', '2764-fe0f-200d-1fa79', 'mending-heart'],
    ['🖤', '1f5a4', 'black-heart'],
    ['🤍', '1f90d', 'white-heart'],
    ['🧠', '1f9e0', 'brain'],
    ['🫀', '1fac0', 'anatomical-heart'],
  ],
};

Object.keys(emojis).forEach(category => {
  emojis[category].forEach(emoji => {
    addIcon(emoji[2], {
      body: twemojis.icons[emoji[2]].body,
      width: 36,
      height: 36,
    });
  });
});

Object.entries({
  'u-upload': 'upload-alt',
  'f-move-left': 'arrow-export-rtl-24-regular',
  'f-move-right': 'arrow-export-ltr-24-regular',
  'f-backspace': 'backspace-24-regular',
  'f-hint': 'square-hint-sparkles-24-filled',
}).forEach(([name, icon]) => {
  addIcon(name, {
    body: (name[0] === 'u' ? unicons : fluent).icons[icon].body,
    width: 24,
    height: 24,
  });
});

export default emojis;
